const mongoose = require("mongoose")
const Schemas = new mongoose.Schema({
  firstname: { type: "string" },
  middlename: { type: "string" },
  lastname: { type: "string" },
  course: { type: "string" },
  aadhar: { type: "string" },
  department: { type: "string" },
  currentyear: { type: "string" },
  dob: { type: "string" },
  yearofjoining: { type: "string" },
  gender: { type: "string" },
  permanentaddress: { type: "string" },
  currentaddress: { type: "string" },
  aadharno: { type: "string" },
  panno: { type: "string" },
  rank: { type: "string" },
  fathername: { type: "string" },
  religion: { type: "string" },
  admissionquota: { type: "string" },
  havinglaptop: { type: "string" },
  mothername: { type: "string" },
  verified: { type: "string" },
  verifiedby: { type: "string" },
  freeze: { type: "string" },
  mobile: { type: "string" },
  tenyear: { type: "string" },
  interyear: { type: "string" },
  tenthboard: { type: "string" },
  interboard: { type: "string" },
  resume: { type: "string" },
  resumelink: { type: "string" },
  pan: { type: "string" },
  tenthmarksheet: { type: "string" },
  intermarksheet: { type: "string" },
  graduationmarksheet: { type: "string" },
  intermpc: { type: "string" },
  caste: { type: "string" },
  altmail: { type: "string" },
  profilepic: { type: "string" },
  companyexperience: { type: "string" },
  rollnumber: { type: "string", unique: true },
  mail: { type: "string", index: { unique: true, dropDups: true } },
  tenthschoolname: { type: "string" },
  tenthcgpa: { type: "string" },
  interclgname: { type: "string" },
  intercgpa: { type: "string" },
  course: { type: "string" },
  sgpa: { type: "Array" },
  cgpa: { type: "string" },
  totalbacklogs: { type: "string" },
  ongoingbacklogs: { type: "string" },
  educationgap: { type: "string" },
  resume: { type: "string" },
  college_id: { type: "string" },
})

module.exports =
  mongoose.models.Schemas || mongoose.model("studentData", Schemas)
